[package]
name = "scylla-cdc-replicator"
version = "0.1.10"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scylla = { workspace = true }
scylla-cdc = { workspace = true }
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
anyhow = { workspace = true }
itertools = { workspace = true }
uuid = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
scylla-cdc-test-utils = { workspace = true }
rstest = { workspace = true }
