[package]
name = "scylla-cdc"
version = "0.6.3"
edition = "2024"
description = "Library for consuming ScyllaDB CDC log for Rust"
repository = "https://github.com/scylladb/scylla-cdc-rust"
readme = "../README.md"
keywords = ["database", "scylla", "cdc"]
categories = ["database"]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
scylla = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
num_enum = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
itertools = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
rand = { workspace = true }
scylla-cdc-test-utils = { workspace = true }
# To compile one of the doc tests, we need rt-multi-thread feature.
tokio = { workspace = true, features = ["rt-multi-thread"] }
rstest = { workspace = true }
